[package]
name = "rustproxyparser"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.10"
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
url = "2.2"
boa_engine = "0.17"
cocoa = "0.24"
core-foundation = "0.9"
core-foundation-sys = "0.8"
scopeguard = "1.1"
regex = "1.10"
system-configuration = "0.5"
core_foundation = "0.9"


[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winhttp", "winbase", "errhandlingapi"] }

[target.'cfg(macos)'.dependencies]
system-configuration = "0.5"
